# Generated by Django 3.1.7 on 2021-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IDusuario', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('Usuario', models.CharField(max_length=20, verbose_name='Nombre usuario')),
                ('contraseña', models.CharField(blank=True, max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
