# Generated by Django 3.1.7 on 2021-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='IDusuario',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Usuario'),
        ),
    ]
