# Generated by Django 3.1.7 on 2021-07-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210707_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='IDusuario',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Usuario'),
        ),
    ]
