# Generated by Django 3.1.7 on 2021-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210707_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='nombre')),
                ('email', models.CharField(max_length=300, verbose_name='email')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
