# Generated by Django 3.1.7 on 2021-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210708_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
