# Generated by Django 3.1.7 on 2021-07-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vehiculo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotosinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
