# Generated by Django 3.1.7 on 2021-07-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fotosinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosinfo',
            name='tipo',
            field=models.CharField(max_length=10, null=True, verbose_name='tipo'),
        ),
    ]
